sudo: required

services:
  - docker

before_script:
  - docker pull blam/go-build:latest

script:
  - docker run --rm -v "$(pwd):/go/src/github.com/benjdlambert/goraphite" blam/go-build github.com/benjdlambert/goraphite build
  - docker run --rm -v "$(pwd):/go/src/github.com/benjdlambert/goraphite" blam/go-build github.com/benjdlambert/goraphite test
  - docker run --rm -v "$(pwd):/go/src/github.com/benjdlambert/goraphite" blam/go-build github.com/benjdlambert/goraphite/query test
